package com.cleevio.watchshopservice.model;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigInteger;

/**
 * Watch domain object.
 */
@Entity
@Table(name = "watches")
@Getter
@Setter
public class Watch {

    /**
     * Watch id, generated by database.
     */
    @Id
    @Column(name = "watch_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long watchId;

    /**
     * Watch title.
     */
    @Column(name = "title")
    private String title;

    /**
     * Watch price.
     */
    @Column(name = "price")
    private BigInteger price;

    /**
     * Watch description.
     */
    @Column(name = "description")
    private String description;

    /**
     * Watch fountain image, base64 encoded.
     */
    @Column(name = "fountain")
    private String fountainImageBase64;
}
